output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: false
max-line-length: 120

ignore-paths:
  - docs/

black:
  run: true

frosted:
  run: false

pyroma:
  run: true

mypy:
  run: true
  options:
    ignore-missing-imports: true
    follow-imports: skip

pylint:
  disable:
    - bad-builtin
    - too-few-public-methods
    - missing-docstring
    - star-args

pep8:
  full: true
  disable:
    - E126

pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D205
    - D400
    - D401
